// <auto-generated />
using System;
using Fair_Share_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fair_Share_Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260306044426_TrackedTaskInIndividualTeam")]
    partial class TrackedTaskInIndividualTeam
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fair_Share_Backend.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text")
                        .HasColumnName("google_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.HasKey("Id")
                        .HasName("account_pkey");

                    b.ToTable("account");
                });

            modelBuilder.Entity("Fair_Share_Backend.Entities.AccountTask", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer")
                        .HasColumnName("task_id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("assigned_at");

                    b.HasKey("AccountId", "TaskId")
                        .HasName("account_task_pkey");

                    b.HasIndex("TaskId");

                    b.ToTable("account_task");
                });

            modelBuilder.Entity("Fair_Share_Backend.Entities.AccountTaskPreference", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer")
                        .HasColumnName("task_id");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.HasKey("AccountId", "TaskId");

                    b.HasIndex("TaskId");

                    b.ToTable("account_task_preference");
                });

            modelBuilder.Entity("Fair_Share_Backend.Entities.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AutoAssignAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("auto_assign_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("DueAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("due_at");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_completed");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<int>("TeamOwnedId")
                        .HasColumnType("integer")
                        .HasColumnName("team_owned_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("task_pkey");

                    b.HasIndex("TeamOwnedId");

                    b.ToTable("task");
                });

            modelBuilder.Entity("Fair_Share_Backend.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("team_pkey");

                    b.ToTable("team");
                });

            modelBuilder.Entity("TeamAccount", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.HasKey("AccountId", "TeamId")
                        .HasName("team_account_pkey");

                    b.HasIndex("TeamId");

                    b.ToTable("team_account", (string)null);
                });

            modelBuilder.Entity("Fair_Share_Backend.Entities.AccountTask", b =>
                {
                    b.HasOne("Fair_Share_Backend.Entities.Account", "Account")
                        .WithMany("AccountTasks")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("account_task_account_id_fkey");

                    b.HasOne("Fair_Share_Backend.Entities.Task", "Task")
                        .WithMany("AccountTasks")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("account_task_task_id_fkey");

                    b.Navigation("Account");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Fair_Share_Backend.Entities.AccountTaskPreference", b =>
                {
                    b.HasOne("Fair_Share_Backend.Entities.Account", "Account")
                        .WithMany("AccountTaskPreferences")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fair_Share_Backend.Entities.Task", "Task")
                        .WithMany("AccountTaskPreferences")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Fair_Share_Backend.Entities.Task", b =>
                {
                    b.HasOne("Fair_Share_Backend.Entities.Team", "TeamOwned")
                        .WithMany("Tasks")
                        .HasForeignKey("TeamOwnedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("task_team_owned_id_fkey");

                    b.Navigation("TeamOwned");
                });

            modelBuilder.Entity("TeamAccount", b =>
                {
                    b.HasOne("Fair_Share_Backend.Entities.Account", "Account")
                        .WithMany("TeamAccounts")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("team_account_account_id_fkey");

                    b.HasOne("Fair_Share_Backend.Entities.Team", "Team")
                        .WithMany("TeamAccounts")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("team_account_team_id_fkey");

                    b.Navigation("Account");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Fair_Share_Backend.Entities.Account", b =>
                {
                    b.Navigation("AccountTaskPreferences");

                    b.Navigation("AccountTasks");

                    b.Navigation("TeamAccounts");
                });

            modelBuilder.Entity("Fair_Share_Backend.Entities.Task", b =>
                {
                    b.Navigation("AccountTaskPreferences");

                    b.Navigation("AccountTasks");
                });

            modelBuilder.Entity("Fair_Share_Backend.Entities.Team", b =>
                {
                    b.Navigation("Tasks");

                    b.Navigation("TeamAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
