// <auto-generated />
using System;
using Fair_Share_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fair_Share_Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fair_Share_Backend.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("member_pkey");

                    b.ToTable("member");
                });

            modelBuilder.Entity("Fair_Share_Backend.Models.MemberTask", b =>
                {
                    b.Property<int>("MemberId")
                        .HasColumnType("integer")
                        .HasColumnName("member_id");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer")
                        .HasColumnName("task_id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("assigned_at");

                    b.HasKey("MemberId", "TaskId")
                        .HasName("member_task_pkey");

                    b.HasIndex("TaskId");

                    b.ToTable("member_task");
                });

            modelBuilder.Entity("Fair_Share_Backend.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("team_pkey");

                    b.ToTable("team");
                });

            modelBuilder.Entity("Fair_Share_Backend.Models.TeamTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AutoAssignAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("auto_assign_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("DueAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("due_at");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_completed");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("task_pkey");

                    b.ToTable("task");
                });

            modelBuilder.Entity("MemberTeam", b =>
                {
                    b.Property<int>("MemberId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("MemberId", "TeamId");

                    b.ToTable("MemberTeam");
                });

            modelBuilder.Entity("TeamMember", b =>
                {
                    b.Property<int>("MemberId")
                        .HasColumnType("integer")
                        .HasColumnName("member_id");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.HasKey("MemberId", "TeamId")
                        .HasName("team_member_pkey");

                    b.HasIndex("TeamId");

                    b.ToTable("team_member", (string)null);
                });

            modelBuilder.Entity("Fair_Share_Backend.Models.MemberTask", b =>
                {
                    b.HasOne("Fair_Share_Backend.Models.Member", "Member")
                        .WithMany("MemberTasks")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("member_task_member_id_fkey");

                    b.HasOne("Fair_Share_Backend.Models.TeamTask", "Task")
                        .WithMany("MemberTasks")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("member_task_task_id_fkey");

                    b.Navigation("Member");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TeamMember", b =>
                {
                    b.HasOne("Fair_Share_Backend.Models.Member", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("team_member_member_id_fkey");

                    b.HasOne("Fair_Share_Backend.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("team_member_team_id_fkey");
                });

            modelBuilder.Entity("Fair_Share_Backend.Models.Member", b =>
                {
                    b.Navigation("MemberTasks");
                });

            modelBuilder.Entity("Fair_Share_Backend.Models.TeamTask", b =>
                {
                    b.Navigation("MemberTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
