api-version: 2024-02-02-preview
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    runtime:
      dotnet:
        autoConfigureDataProtection: true
    ingress:
      external: false
      targetPort: 8080
      transport: http
      allowInsecure: true
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
    secrets:
      - name: connectionstrings--postgres
        value: Host=postgres;Port=5432;Username=postgres;Password={{ securedParameter "postgres_password" }}
      - name: postgres-password
        value: '{{ securedParameter "postgres_password" }}'
  template:
    containers:
      - image: {{ .Image }}
        name: fair-share-functions
        env:
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
          - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
            value: "true"
          - name: ASPNETCORE_URLS
            value: http://+:8080
          - name: Aspire__Azure__Data__Tables__AzureWebJobsStorage__ServiceUri
            value: '{{ .Env.FUNCSTORAGED5B14_TABLEENDPOINT }}'
          - name: Aspire__Azure__Messaging__ServiceBus__serviceBus__FullyQualifiedNamespace
            value: '{{ .Env.SERVICEBUS_SERVICEBUSENDPOINT }}'
          - name: Aspire__Azure__Storage__Blobs__AzureWebJobsStorage__ServiceUri
            value: '{{ .Env.FUNCSTORAGED5B14_BLOBENDPOINT }}'
          - name: Aspire__Azure__Storage__Files__DataLake__AzureWebJobsStorage__ServiceUri
            value: '{{ .Env.FUNCSTORAGED5B14_DATALAKEENDPOINT }}'
          - name: Aspire__Azure__Storage__Queues__AzureWebJobsStorage__ServiceUri
            value: '{{ .Env.FUNCSTORAGED5B14_QUEUEENDPOINT }}'
          - name: AzureFunctionsJobHost__telemetryMode
            value: OpenTelemetry
          - name: AzureWebJobsStorage__blobServiceUri
            value: '{{ .Env.FUNCSTORAGED5B14_BLOBENDPOINT }}'
          - name: AzureWebJobsStorage__dataLakeServiceUri
            value: '{{ .Env.FUNCSTORAGED5B14_DATALAKEENDPOINT }}'
          - name: AzureWebJobsStorage__queueServiceUri
            value: '{{ .Env.FUNCSTORAGED5B14_QUEUEENDPOINT }}'
          - name: AzureWebJobsStorage__tableServiceUri
            value: '{{ .Env.FUNCSTORAGED5B14_TABLEENDPOINT }}'
          - name: FUNCTIONS_WORKER_RUNTIME
            value: dotnet-isolated
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY
            value: in_memory
          - name: POSTGRES_HOST
            value: postgres
          - name: POSTGRES_JDBCCONNECTIONSTRING
            value: jdbc:postgresql://postgres:5432
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_URI
            value: postgresql://postgres:{{ uriEncode (securedParameter "postgres_password" )}}@postgres:5432
          - name: POSTGRES_USERNAME
            value: postgres
          - name: serviceBus__fullyQualifiedNamespace
            value: '{{ .Env.SERVICEBUS_SERVICEBUSENDPOINT }}'
          - name: ConnectionStrings__postgres
            secretRef: connectionstrings--postgres
          - name: POSTGRES_PASSWORD
            secretRef: postgres-password
    scale:
      minReplicas: 1
tags:
  azd-service-name: fair-share-functions
  aspire-resource-name: fair-share-functions
